services:
  - type: web
    name: knowo-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /open-app
        destination: /open-app.html
      - type: rewrite
        source: /*
        destination: /index.html
